version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: index_study
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./src/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  node:
    image: node:22-alpine
    volumes:
      - .:/app
      - ./data/node_modules:/app/node_modules
    working_dir: /app
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=index_study
    depends_on:
      mysql:
        condition: service_healthy
    command: tail -f /dev/null 